/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTutorRouteImport } from './routes/api/tutor'
import { Route as CoachThreadIdRouteImport } from './routes/coach.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTutorRoute = ApiTutorRouteImport.update({
  id: '/api/tutor',
  path: '/api/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachThreadIdRoute = CoachThreadIdRouteImport.update({
  id: '/coach/$threadId',
  path: '/coach/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/tutor': typeof ApiTutorRoute
  '/coach/$threadId': typeof CoachThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/tutor': typeof ApiTutorRoute
  '/coach/$threadId': typeof CoachThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/tutor': typeof ApiTutorRoute
  '/coach/$threadId': typeof CoachThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/tutor' | '/coach/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/tutor' | '/coach/$threadId'
  id: '__root__' | '/' | '/api/tutor' | '/coach/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTutorRoute: typeof ApiTutorRoute
  CoachThreadIdRoute: typeof CoachThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tutor': {
      id: '/api/tutor'
      path: '/api/tutor'
      fullPath: '/api/tutor'
      preLoaderRoute: typeof ApiTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/$threadId': {
      id: '/coach/$threadId'
      path: '/coach/$threadId'
      fullPath: '/coach/$threadId'
      preLoaderRoute: typeof CoachThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTutorRoute: ApiTutorRoute,
  CoachThreadIdRoute: CoachThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
